spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

    datasource:
      url: jdbc:h2:mem:notificationdb
      driverClassName: org.h2.Driver
      username: sa
      password:
jpa:
  hibernate:
    ddl-auto: update

  jms:
    listener:
      acknowledge-mode: auto
      concurrency: 5
resilience4j:
  circuitbreaker:
    instances:
      clientListenerBreaker:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  application:
    name: notification

